project:
  type: website
  output-dir: docs

website:
  title: "Daniel Marris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
      - href: otherbits.qmd
        text: Other Bits
  favicon: images\\fav.png
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



