project:
  type: website
  output-dir: docs

website:
  title: "Daniel Marris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
      - href: otherbits.qmd
        text: Other Bits
  favicon: images\\fav.png

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
  
    css: styles.css
    toc: true

html:
  meta:
    - name: description
      content: "The personal website of Daniel Marris. Find information about my research on stochastic processes and random walks, see my publications, and 
      find contact details."


